version: "3"
services:

  subaligner-centos7:
    build:
      context: ./
      dockerfile: Dockerfile-CentOS7
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.el7

  subaligner-ubuntu18:
    build:
      context: ./
      dockerfile: Dockerfile-Ubuntu18
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.u18

  subaligner-ubuntu20:
    build:
      context: ./
      dockerfile: Dockerfile-Ubuntu20
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.u20

  subaligner-archlinux:
    build:
      context: ./
      dockerfile: Dockerfile-ArchLinux
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.arch

  subaligner-debian10:
    build:
      context: ./
      dockerfile: Dockerfile-Debian11
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.deb11

  subaligner-fedora31:
    build:
      context: ./
      dockerfile: Dockerfile-Fedora37
    image: baxtree/subaligner:${SUBALIGNER_VERSION}.fed37
